name = "PublicationFiguresMakie"
uuid = "11f6ef32-7dbc-428f-9c1a-e2165be35776"
authors = ["Riccardo Foffi <riccardo.foffi@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
